### ISSUE TITLE
Camera ID for CCVID 

### ISSUE THREAD

**Issue by levan92** [guxinqian/Simple-CCReID#10]
Hi, 

Thank you for providing CCVID dataset. 

I refer to your code for processing CCVID at these lines: 
https://github.com/guxinqian/Simple-CCReID/blob/f773d013508a7697f09ff0ca5f1622dfc46aa531/data/datasets/ccvid.py#L151-L156

How is Camera ID determined? I read through [FVG](http://cvlab.cse.msu.edu/pdfs/Zhang_Tran_Yin_Atoum_Liu_Wan_Wang_CVPR2019.pdf)'s paper, If I am not wrong, the the tracklet folders are named according to "{person id}_{walk index}" (each subject walk 12 times: 3 angles x 4 walking speeds). I understand your rationale of splitting them by "walk index" within each session. But based on the lines I referenced above, it seems like only session 3 has a "+12", meaning same walk indices in sessions 1 and 2 are treated as the same camera, but from what I see, the camera for session 1 and 2 are placed at different locations (different backgrounds).

**Comment by levan92** [comment]
Another point, seems like if we want to closely imitate the effects of different "Camera ID" as different "backgrounds", we should be splitting by "walking angles" instead. For example, in tracklets `session1/084_*` : `084_02`, `084_05`, `084_08`, `084_11` have the same background as they have the same "walking angle", therefore, they should have the same "Camera ID"?

**Comment by guxinqian** [comment]
Yeah, as you mentioned, FVG doesn't privde camera ID. In evaluation, the evaluation function would remove the ground truth samples from the same camera ID. Since we only focus on cross-clothes accuracy and don't care camera, we just use the walking index as the camera ID. In this case, all samples of the same person have different camera ID and wouldn't be removed from the ground truth set in evaluation.
The identities of the samples from Section 3 is the subset of Section 1&2. To avoid the same problem, we set"camid = int(cam) + 12 ".

**Comment by levan92** [comment]
Alright, thank you for your reply!
