### ISSUE TITLE
about PRCC evaluation

### ISSUE THREAD

**Issue by QizaoWang** [guxinqian/Simple-CCReID#7]
Hello! 
For PRCC dataset, it used single-shot matching by randomly choosing one image of each identity as gallery. I notice in your code, you define "gallery_idx" in the "PRCC" class, but it is not used elsewhere. 
Whether the result in the paper is got by using all gallery data (i.e. multi-shot matching) of PRCC?

**Comment by guxinqian** [comment]
Yes, the result in the paper is got by multi-shot matching, since the result of multi-shot matching is more stable than the averaged result of ten single-shot matchings. About half of SOTA methods use single-shot matching and the others use multi-shot matching (using mAP in their comparisons). These two evaluation metrics can get close top-1 acc.

If you want to use single-shot matching, you can replace the code for acc calculation in test_prcc with the following code:
```
cmc_same = []
cmc_diff = []
# Cosine similarity
qsf = F.normalize(qsf, p=2, dim=1)
qdf = F.normalize(qdf, p=2, dim=1)
gf = F.normalize(gf, p=2, dim=1)
for idx in range(0, 10):
    gf_split = gf[gallery_idx[idx]]
    m, n, k = qsf.size(0), qdf.size(0), gf_split.size(0)
    distmat_same = torch.zeros((m,k))
    distmat_diff = torch.zeros((n,k))
    for i in range(m):
        distmat_same[i] = - torch.mm(qsf[i:i+1], gf_split.t())
    for i in range(n):
        distmat_diff[i] = - torch.mm(qdf[i:i+1], gf_split.t())
    distmat_same = distmat_same.numpy()
    distmat_diff = distmat_diff.numpy()
    cmc, _ = evaluate(distmat_same, qs_pids, g_pids[gallery_idx[idx]], qs_camids, g_camids[gallery_idx[idx]])
    cmc_same.append(np.expand_dims(cmc, axis=0))
    cmc, _ = evaluate(distmat_diff, qd_pids, g_pids[gallery_idx[idx]], qd_camids, g_camids[gallery_idx[idx]])
    cmc_diff.append(np.expand_dims(cmc, axis=0))
cmc_same = np.concatenate(cmc_same, axis=0).mean(0)
cmc_diff = np.concatenate(cmc_diff, axis=0).mean(0)
```
